# Generated by Django 5.2.6 on 2025-09-06 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='اللون الأساسي الأول')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='اللون الأساسي الثاني')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إعدادات المظهر',
                'verbose_name_plural': 'إعدادات المظهر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'إدارة'), ('entity', 'كيان'), ('candidate', 'مرشح'), ('pillar', 'ركيزة')], default='pillar', max_length=20),
        ),
    ]
