# Generated by Django 5.2.6 on 2025-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_appearancesettings_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='border_radius',
            field=models.IntegerField(default=8, verbose_name='انحناء الحواف (px)'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='danger_color',
            field=models.CharField(default='#dc3545', max_length=7, verbose_name='لون الخطر'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='font_family',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Tajawal', 'Tajawal'), ('Amiri', 'Amiri'), ('Noto Sans Arabic', 'Noto Sans Arabic'), ('system-ui', 'النظام الافتراضي')], default='Cairo', max_length=50, verbose_name='نوع الخط'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='font_size',
            field=models.IntegerField(default=14, verbose_name='حجم الخط الأساسي (px)'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='info_color',
            field=models.CharField(default='#17a2b8', max_length=7, verbose_name='لون المعلومات'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='sidebar_width',
            field=models.IntegerField(default=280, verbose_name='عرض الشريط الجانبي (px)'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='success_color',
            field=models.CharField(default='#28a745', max_length=7, verbose_name='لون النجاح'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'الوضع النهاري'), ('dark', 'الوضع الليلي'), ('auto', 'تلقائي')], default='light', max_length=10, verbose_name='وضع المظهر'),
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='warning_color',
            field=models.CharField(default='#ffc107', max_length=7, verbose_name='لون التحذير'),
        ),
        migrations.AlterField(
            model_name='appearancesettings',
            name='primary_color',
            field=models.CharField(default='#667eea', max_length=7, verbose_name='اللون الأساسي الأول'),
        ),
        migrations.AlterField(
            model_name='appearancesettings',
            name='secondary_color',
            field=models.CharField(default='#764ba2', max_length=7, verbose_name='اللون الأساسي الثاني'),
        ),
    ]
