# Generated by Django 5.2.6 on 2025-09-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_appearancesettings_border_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearancesettings',
            name='border_radius',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='danger_color',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='sidebar_width',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='theme_mode',
        ),
        migrations.RemoveField(
            model_name='appearancesettings',
            name='warning_color',
        ),
        migrations.AddField(
            model_name='appearancesettings',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='لون نص الأزرار'),
        ),
        migrations.AlterField(
            model_name='appearancesettings',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='اللون الأساسي الأول'),
        ),
        migrations.AlterField(
            model_name='appearancesettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='اللون الأساسي الثاني'),
        ),
    ]
