# Generated by Django 5.2.6 on 2025-09-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_remove_appearancesettings_border_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearancesettings',
            name='card_title_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='لون عنوان البطاقة'),
        ),
    ]
