# Generated by Django 5.2.6 on 2025-09-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_appearancesettings_card_title_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
